plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
theme: jekyll-theme-tactile
title: David Finol
resume_url: https://registry.jsonresume.org/davidmfinol
linkedin_url: https://www.linkedin.com/in/davidmfinol
url: 'https://davidmfinol.me'
