plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
theme: jekyll-theme-tactile
title: David Finol
resume_url: ./RESUME.pdf
linkedin_url: https://www.linkedin.com/in/davidmfinol
url: 'https://davidmfinol.me'
